sudo: required
dist: trusty

language: node_js
node_js:
  - '5.6.0'

branches:
  only:
  - master

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
 - npm install -g angular-cli
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start

script:
 - ng test --single-run
 - ng serve &
 - ng e2e